### PR TITLE
Scrum 12 users should be able to provide feedback on posts including comments and ratings

### PR DESCRIPTION
**Pull request by krwro**

### CODE REVIEW

**Comment by r-carissimi** [comment]
Great commit. Should we also edit the "init-dynamodb-lockalstack.sh" script to automatically create dynamodb tables?

**Comment by krwro** [comment]
No, the script creates a table named "Posts". Since all objects are in the same table, no adjustment is necessary.

**Review by ovanov — APPROVED** [review]
Looks really good. Very nice :)
I really like the profile specific setting, but right now, the profiles are identical. Are the `.propery` files intended to be identical?

**Comment by krwro** [comment]
> Looks really good. Very nice :) I really like the profile specific setting, but right now, the profiles are identical. Are the `.propery` files intended to be identical?

Right now, it is fine that the property files are identical. The main point was to make the SDK table initialization work only for tests and development. I read somewhere that the Lamda overrides the environment variables anyway, so there might be no changes to the properties file necessary, but I will look into it again. Thanks for the review :)

**Pull request merged**
